name: "arr_modeling"
version: "1.0.0"

profile: "arr_profile"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
    - "target"
    - "dbt_packages"

tests:
    arr_modeling:
        +store_failures: true
        +store_failures_as: table
        +schema: audit

models:
    arr_modeling:
        staging:
            +materialized: view
        intermediate:
            +materialized: ephemeral
        marts:
            +materialized: table
